#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v4
# autospec commit: 1ab68ca
#
Name     : R-flextable
Version  : 0.9.5
Release  : 27
URL      : https://cran.r-project.org/src/contrib/flextable_0.9.5.tar.gz
Source0  : https://cran.r-project.org/src/contrib/flextable_0.9.5.tar.gz
Summary  : Functions for Tabular Reporting
Group    : Development/Tools
License  : GPL-3.0
Requires: R-data.table
Requires: R-gdtools
Requires: R-htmltools
Requires: R-knitr
Requires: R-officer
Requires: R-ragg
Requires: R-rlang
Requires: R-rmarkdown
Requires: R-uuid
Requires: R-xml2
BuildRequires : R-data.table
BuildRequires : R-gdtools
BuildRequires : R-htmltools
BuildRequires : R-knitr
BuildRequires : R-officer
BuildRequires : R-ragg
BuildRequires : R-rlang
BuildRequires : R-rmarkdown
BuildRequires : R-uuid
BuildRequires : R-xml2
BuildRequires : buildreq-R

%description
flextable R package
================
[![R build
status](https://github.com/davidgohel/flextable/workflows/R-CMD-check/badge.svg)](https://github.com/davidgohel/flextable/actions)
[![version](https://www.r-pkg.org/badges/version/flextable)](https://CRAN.R-project.org/package=flextable)
![Active](https://www.repostatus.org/badges/latest/active.svg)

%prep
%setup -q -n flextable
pushd ..
cp -a flextable buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709742074

%install
export SOURCE_DATE_EPOCH=1709742074
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/flextable/DESCRIPTION
/usr/lib64/R/library/flextable/INDEX
/usr/lib64/R/library/flextable/Meta/Rd.rds
/usr/lib64/R/library/flextable/Meta/features.rds
/usr/lib64/R/library/flextable/Meta/hsearch.rds
/usr/lib64/R/library/flextable/Meta/links.rds
/usr/lib64/R/library/flextable/Meta/nsInfo.rds
/usr/lib64/R/library/flextable/Meta/package.rds
/usr/lib64/R/library/flextable/Meta/vignette.rds
/usr/lib64/R/library/flextable/NAMESPACE
/usr/lib64/R/library/flextable/NEWS.md
/usr/lib64/R/library/flextable/R/flextable
/usr/lib64/R/library/flextable/R/flextable.rdb
/usr/lib64/R/library/flextable/R/flextable.rdx
/usr/lib64/R/library/flextable/doc/index.html
/usr/lib64/R/library/flextable/doc/overview.Rmd
/usr/lib64/R/library/flextable/doc/overview.html
/usr/lib64/R/library/flextable/examples/rmd/captions_example.Rmd
/usr/lib64/R/library/flextable/examples/rmd/demo.Rmd
/usr/lib64/R/library/flextable/examples/rmd/loop_with_flextable.Rmd
/usr/lib64/R/library/flextable/flextablelogo.svg
/usr/lib64/R/library/flextable/help/AnIndex
/usr/lib64/R/library/flextable/help/aliases.rds
/usr/lib64/R/library/flextable/help/figures/README-diamonds-dataset-1.png
/usr/lib64/R/library/flextable/help/figures/README-mtcars-dataset-1.png
/usr/lib64/R/library/flextable/help/figures/README-mtcars-dataset-2.png
/usr/lib64/R/library/flextable/help/figures/fig_formats.png
/usr/lib64/R/library/flextable/help/figures/logo.png
/usr/lib64/R/library/flextable/help/flextable.rdb
/usr/lib64/R/library/flextable/help/flextable.rdx
/usr/lib64/R/library/flextable/help/paths.rds
/usr/lib64/R/library/flextable/html/00Index.html
/usr/lib64/R/library/flextable/html/R.css
/usr/lib64/R/library/flextable/tests/testthat.R
/usr/lib64/R/library/flextable/tests/testthat/rmd/bookdown.Rmd
/usr/lib64/R/library/flextable/tests/testthat/rmd/borders.Rmd
/usr/lib64/R/library/flextable/tests/testthat/rmd/captions.Rmd
/usr/lib64/R/library/flextable/tests/testthat/rmd/rmarkdown.Rmd
/usr/lib64/R/library/flextable/tests/testthat/test-as-flextable.R
/usr/lib64/R/library/flextable/tests/testthat/test-as_flextable.R
/usr/lib64/R/library/flextable/tests/testthat/test-borders.R
/usr/lib64/R/library/flextable/tests/testthat/test-captions-rmd.R
/usr/lib64/R/library/flextable/tests/testthat/test-cell-content.R
/usr/lib64/R/library/flextable/tests/testthat/test-dimensions.R
/usr/lib64/R/library/flextable/tests/testthat/test-errors.R
/usr/lib64/R/library/flextable/tests/testthat/test-footers.R
/usr/lib64/R/library/flextable/tests/testthat/test-footnote.R
/usr/lib64/R/library/flextable/tests/testthat/test-gen_grob.R
/usr/lib64/R/library/flextable/tests/testthat/test-headers.R
/usr/lib64/R/library/flextable/tests/testthat/test-images.R
/usr/lib64/R/library/flextable/tests/testthat/test-keep-next.R
/usr/lib64/R/library/flextable/tests/testthat/test-latex.R
/usr/lib64/R/library/flextable/tests/testthat/test-link.R
/usr/lib64/R/library/flextable/tests/testthat/test-md-captions.R
/usr/lib64/R/library/flextable/tests/testthat/test-merge.R
/usr/lib64/R/library/flextable/tests/testthat/test-misc.R
/usr/lib64/R/library/flextable/tests/testthat/test-new-rows.R
/usr/lib64/R/library/flextable/tests/testthat/test-padding.R
/usr/lib64/R/library/flextable/tests/testthat/test-pptx-tables.R
/usr/lib64/R/library/flextable/tests/testthat/test-proc-freq.R
/usr/lib64/R/library/flextable/tests/testthat/test-rotations.R
/usr/lib64/R/library/flextable/tests/testthat/test-styles.R
/usr/lib64/R/library/flextable/tests/testthat/test-text.R
/usr/lib64/R/library/flextable/tests/testthat/zzzzz.R
/usr/lib64/R/library/flextable/web_1.1.3/tabwid.css
/usr/lib64/R/library/flextable/web_1.1.3/tabwid.js
